// TODO: Review from scratch

export const LOG_ERROR = 'LOG_ERROR'

export const SUGGEST_VENDOR_NAMES = 'SUGGEST_VENDOR_NAMES'
export const SUGGEST_PRODUCT_NAMES = 'SUGGEST_PRODUCT_NAMES'
export const SUGGEST_PRODUCT_VERSIONS = 'SUGGEST_PRODUCT_VERSIONS'
export const SET_VENDOR_NAME_SUGGESTIONS = 'SET_VENDOR_NAME_SUGGESTIONS'
export const SET_PRODUCT_NAME_SUGGESTIONS = 'SET_PRODUCT_NAME_SUGGESTIONS'
export const SET_PRODUCT_VERSION_SUGGESTIONS = 'SET_PRODUCT_VERSION_SUGGESTIONS'
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS'

export const REFRESH_RISKS = 'REFRESH_RISKS'
export const SET_RISKS = 'SET_RISKS'
export const SET_TASK = 'SET_TASK'
export const SET_SELECTED_RISK_INDEX = 'SET_SELECTED_RISK_INDEX'
